---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: flask-app
  name: python-app
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: 211125415085.dkr.ecr.us-east-1.amazonaws.com/flask-app
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: flask-app
  name: python-service
spec:
  type: NodePort
  selector:  
    app: python-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  
